# Dockerfile.backend
FROM php:8.1-fpm-alpine

COPY --from=composer:2.3 /usr/bin/composer /usr/bin/composer

RUN apk add --no-cache \
    git \
    bash \
    icu-dev \
    libzip-dev \
    oniguruma-dev \
    zip \
    unzip \
    mysql-client

WORKDIR /var/www/backend

CMD ["php-fpm"]
